name: fintel
description: Financial Intelligence Application based on Dohaham method.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # Database
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0 # For Windows/Desktop
  path: ^1.8.3
  
  # Utilities
  intl: ^0.20.0 
  
  # Notifications - הוספת התשתית להתראות ודיופמין פיננסי
  flutter_local_notifications: ^17.0.0
  
  window_manager: ^0.3.9 # For controlling window size on Desktop
  path_provider: ^2.1.5
  firebase_core: ^4.4.0
  cloud_firestore: ^6.1.2
  firebase_auth: ^6.1.4
  google_sign_in: ^7.2.0
  desktop_webview_auth: ^0.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true